### ISSUE TITLE
Exception: Found multiple get_by_name matches, undefined behavior

### ISSUE THREAD

**Issue by sducouedic** [fastmachinelearning/qonnx#30]
Hello, 

When creating the bitfile for a model that I exported from brevitas, the following error is raised during the streamlining step:
```
    model = model.transform(GiveReadableTensorNames())
  File "/tools/Xilinx/finn/deps/qonnx/src/qonnx/core/modelwrapper.py", line 140, in transform
    (transformed_model, model_was_changed) = transformation.apply(transformed_model)
  File "/tools/Xilinx/finn/deps/qonnx/src/qonnx/transformation/general.py", line 135, in apply
    model.rename_tensor(i, "%s_param%d" % (n.name, init_in_num))
  File "/tools/Xilinx/finn/deps/qonnx/src/qonnx/core/modelwrapper.py", line 301, in rename_tensor
    if util.get_by_name(graph.initializer, old_name) is not None:
  File "/tools/Xilinx/finn/deps/qonnx/src/qonnx/util/basic.py", line 82, in get_by_name
    raise Exception("Found multiple get_by_name matches, undefined behavior")
Exception: Found multiple get_by_name matches, undefined behavior
```

### Possible Fix
I observed that two nodes in my model are swapped during the streamlining step (ie. node 13 --> node 14, node 14 --> node 13) step, and as their input tensor are renamed during a `GiveReadableTensorNames` transformation, at some point two input parameters have the same names, which is not supposed to happen because `GiveReadableTensorNames` calls `GiveRandomTensorNames` which is supposed gives random names to **all** the tensors. The error then probably comes from `Model.get_all_tensor_names()`  which probably doesn't actually returns *all* tensor names in the model.

**Comment by maltanar** [comment]
If the problem is coming from streamlining, please report this issue in the [FINN repository](https://github.com/Xilinx/finn/) instead. Also, please provide a concrete testcase (ONNX file and minimal Python script to reproduce the problem).
