### ISSUE TITLE
GiveReadableTensorNames: Exception("Found multiple get_by_name matches, undefined behavior")

### ISSUE THREAD

**Issue by sducouedic** [fastmachinelearning/qonnx#33]
> If the problem is coming from streamlining, please report this issue in the [FINN repository](https://github.com/Xilinx/finn/) instead. Also, please provide a concrete testcase (ONNX file and minimal Python script to reproduce the problem).

Hi I open the issue again, as the error comes from qonnx and not from finn.

## Prerequisites
Please make sure to check off these prerequisites before submitting a bug report.
- [X] Test that the bug appears on the current version of the main branch. Make sure to include the commit hash of the commit you checked out. [7d50273](https://github.ibm.com/Sophie-Du-Couedic/DNNQuantization/commit/0bf0b66005541d73cf9cc75a0857a22de4e7ef58)
- [X] Check that the issue hasn't already been reported, by checking the currently open issues.
- [X] If there are steps to reproduce the problem, make sure to write them down below.
- [X] If relevant, please include the ONNX files, which were created directly before and/or after the bug. **onxx model generated in the python script**

## Quick summary
If the model misses a tensor shape for one the inputs or outputs of a node, then the model is not able to rename the tensors correctly.

## Details and Fix
Here is the execution trace:
* `GiveReadableTensorNames` first gives tensors random names (`GiveRandomTensorNames`) which supposely avoid the error above of duplicate names. 
* `GiveRandomTensorNames` retrieve all the tensor names (`ModelWrapper.get_all_tensor_names`) which **doesn't return graph.initializer names**. Therefore a first fix is to add the initializers tensor to the returned names in `ModelWrapper.get_all_tensor_names`:
   ```python
    def get_all_tensor_names(self):
        """Returns a list of all (input, output and value_info) tensor names
        in the graph."""
        graph = self.graph
        names = [x.name for x in graph.value_info]
        names += [x.name for x in graph.input]
        names += [x.name for x in graph.output]
        # fix
        names += [x.name for x in graph.initializer]  
        return names
   ```
* But when ModelWrapper loads a model, it automatically add all initializer tensors to graph.value_info:
   ```python
      class ModelWrapper:
          def __init__(self, [...], fix_missing_initializer_valueinfo=True)
              [...]
              if fix_missing_initializer_valueinfo:
                  self.check_all_tensor_shapes_specified(fix_missing_init_shape=True)
   ```
* The real error then comes from the method `ModelWrapper.check_all_tensor_shapes_specified`. If one tensors of the model misses its shape, then all subsequent tensor shapes are ignored, and are not added to `graph.value_info`. The reason is that the compiler ignores the call to `self.get_tensor_shape` as soon as `ret==False`:
   ```python
   for n in graph.node:
       for i in n.input:
            ret = (self.get_tensor_shape(i, fix_missing_init_shape=fix_missing_init_shape) is not None) and ret  # fix
           # ret = ret and (self.get_tensor_shape(i, fix_missing_init_shape=fix_missing_init_shape) is not None)  # compiler ignores call to method
       for o in n.output:
            ret = (self.get_tensor_shape(o, fix_missing_init_shape=fix_missing_init_shape) is not None) and ret  # fix
           # ret = ret and (self.get_tensor_shape(o, fix_missing_init_shape=fix_missing_init_shape) is not None) # compiler ignores method
   ```

### Steps to Reproduce
Run this snippet of code:
```python3
import onnx
import numpy as np
from qonnx.core.modelwrapper import ModelWrapper
from qonnx.transformation.general import GiveReadableTensorNames, GiveUniqueNodeNames

Add1_node = onnx.helper.make_node(
    'Add',
    inputs=['in1', 'Add_1_param0'],
    outputs=['sum1'],
    name='Add_1'
)

Add0_node = onnx.helper.make_node(
    'Add',
    inputs=['sum1', 'Add_0_param0'],
    outputs=['sum2'],
    name='Add_0',
)

Add2_node = onnx.helper.make_node(
    'Add',
    inputs=['abs1', 'abs1'],
    outputs=['sum3'],
    name='Add_2',
)

Abs_node = onnx.helper.make_node(
    'Abs',
    inputs=['sum2'],
    outputs=['abs1'],
    name='Abs'
)

Round_node = onnx.helper.make_node(
    'Round',
    inputs=['sum3'],
    outputs=['out1'],
    name='Round',
)

in1 = onnx.helper.make_tensor_value_info("in1", onnx.TensorProto.FLOAT, [4, 4])
out1 = onnx.helper.make_tensor_value_info("out1", onnx.TensorProto.FLOAT, [4, 4])

graph = onnx.helper.make_graph(
    nodes=[
        Add1_node,
        Add0_node,
        Abs_node,
        Add2_node,
        Round_node,
    ],
    name="simple_graph",
    inputs=[in1],
    outputs=[out1],
    value_info=[
        # onnx.helper.make_tensor_value_info("sum1", onnx.TensorProto.FLOAT, [4, 4]),
        onnx.helper.make_tensor_value_info("sum2", onnx.TensorProto.FLOAT, [4, 4]),
        onnx.helper.make_tensor_value_info("abs1", onnx.TensorProto.FLOAT, [4, 4]),
        onnx.helper.make_tensor_value_info("sum3", onnx.TensorProto.FLOAT, [4, 4]),
    ],
    initializer=[
        onnx.helper.make_tensor('Add_1_param0', onnx.TensorProto.FLOAT, [4, 4], np.zeros(16).tolist()),
        onnx.helper.make_tensor('Add_0_param0', onnx.TensorProto.FLOAT, [4, 4], np.zeros(16).tolist())
    ]
)

onnx_model = onnx.helper.make_model(graph, producer_name="simple-model")
onnx.save(onnx_model, 'simple_model.onnx')

model = ModelWrapper(onnx_model)
model = model.transform(GiveUniqueNodeNames())
model = model.transform(GiveReadableTensorNames())
```

**Comment by maltanar** [comment]
Thank you @sducouedic for the detalied report, the testcase and tracking down the root of the issue. This is indeed due to Python's short-circuiting behavior for ops like `and`: https://docs.python.org/3/library/stdtypes.html#boolean-operations-and-or-not

I will shortly merge a PR where I've incorporated your testcase and a fix (which is to swap the order of operands to `and` in the `check_all_tensor_shapes_specified` function.
